### ISSUE TITLE
Integration with nuxt-i18n

### ISSUE THREAD

**Issue by manniL** [lewyuburi/nuxt-validate#1]
Hey,

I'm curious if it'd be possible to integrate localization together with [nuxt-i18n](https://github.com/nuxt-community/nuxt-i18n). Vee-validate already works together with vue-i18n (see [here](https://github.com/baianat/vee-validate/pull/1007)), so I guess it's possible :thinking:

**Comment by Extarys** [comment]
Yes, or at least we could change the lang variable when the language is changed in i18n..

**Comment by lvaroqui** [comment]
Does someone has an easy fix to integrate i18n ?

**Comment by lewyuburi** [comment]
> Does someone has an easy fix to integrate i18n ?

I want to work this weekend in this integration

**Comment by lvaroqui** [comment]
Hey, I worked out a little plugin that auto sync language from nuxt-i18n, maybe you can add it to your own plugin ;)

```javascript
//Importing dictionaries for vee-validate
import en from 'vee-validate/dist/locale/en';
import fr from 'vee-validate/dist/locale/fr';
import VeeValidate, {Validator} from 'vee-validate';

export default function ({app}) {
  //Loading languages for Vee
  Validator.localize('en', en);
  Validator.localize('fr', fr);

  //Localizing the app when user refresh or access a localized link
  Validator.localize((app.i18n.loadedLanguages[0]));

  //Called everytime language change
  app.i18n.beforeLanguageSwitch = (oldLocale, newLocale) => {
    Validator.localize(newLocale);
  }
}
```

**Comment by arnaud-large** [comment]
Hey, i've tried your solution but i have a problem, the first keypress no more works with vee-validate, it only works on the second keypress, this is my nuxt config :

`modules: [
    '@nuxtjs/axios',
    ['nuxt-i18n', {
      locales: [
        {
          code: 'en',
          iso: 'en-US',
          file: 'en.json'
        },
        {
          code: 'fr',
          iso: 'fr-FR',
          file: 'fr.json'
        }
      ],
      lazy: true,
      langDir: 'locales/',
      strategy: 'prefix_except_default',
      defaultLocale: 'en',
      vueI18n: {
        fallbackLocale: 'en'
      }
    }],
    'nuxt-validate'
  ],`

If i disable nuxt-i18n then vee-validate works correctly, do you have any idea ?

Thanks for help.

**Comment by lvaroqui** [comment]
I didn't notice but I encounter the same behavior, going to dig into it when I'll have time !

**Comment by chefjuanpi** [comment]
I create two plugins:
```
// i18n,js thanks @lvaroqui for this
import en from 'vee-validate/dist/locale/en'
import es from 'vee-validate/dist/locale/es'
import { Validator } from 'vee-validate'
export default function({ app }) {
  // Loading languages for Vee

  Validator.localize('en', en)
  Validator.localize('es', es)

  // Localizing the app when user refresh or access a localized link
  Validator.localize(app.i18n.loadedLanguages[0])

  // beforeLanguageSwitch called right before setting a new locale
  app.i18n.beforeLanguageSwitch = (oldLocale, newLocale) => {
    Validator.localize(newLocale)
  }
}
```
```
// vee-validate.js
import Vue from 'vue'
import VeeValidate from 'vee-validate'

Vue.use(VeeValidate, {
  inject: false,
  // Important for bootstrap-vue
  fieldsBagName: 'veeFields'
})
```
At the component where I need validation I add:
```
  $_veeValidate: {
    validator: 'new' // give me my own validator scope.
  },
```
this is explain [here](https://baianat.github.io/vee-validate/concepts/injections.html#requesting-a-new-validator-scope)

That's all!

**Comment by FPNL** [comment]
thank you guys, this really bother me for days...
and this is how i fix this problem
```js
// i18n.js thank everyone above
import { Validator } from 'vee-validate'
import EN from 'vee-validate/dist/locale/en'
import TW from 'vee-validate/dist/locale/zh_TW'

//  To fit different name
const forValidator = {
  en: {
    veeDefaultName: 'en',
    dic: EN
  },
  'zh-tw': {
    veeDefaultName: 'zh_TW',
    dic: TW 
  },
}
export default function ({ app }) {
  Validator.localize(app.i18n.locale)
  // beforeLanguageSwitch called right before setting a new locale
  app.i18n.beforeLanguageSwitch = (oldLocale, newLocale) => {
    Validator.localize(forValidator[newLocale][veeDefaultName], forValidator[newLocale][dic])
  }
}
```
```js
plugins: [
    ...,
    { src: '~plugins/i18n.js' },
  ],
```

**Comment by lewyuburi** [comment]
The integration nuxt-i18n was done thanks to @aaharu <3 Docs are in the readme, thanks for supporting :D
