### ISSUE TITLE
Vee-Validate config

### ISSUE THREAD

**Issue by Blemming** [lewyuburi/nuxt-validate#17]
How do I access the vee-validate [config object](https://baianat.github.io/vee-validate/configuration.html) ?
 I tried from the modules:
`modules:[
['nuxt-validate',{
fieldsBagName: 'vFields'
}
]`

but that doesnt work

**Comment by darthf1** [comment]
Looking for this as well. Need to change the fieldsBagName to resolve issues with vue-bootstrap.

https://bootstrap-vue.js.org/docs/reference/validation/#veevalidate

**Comment by EdwinHoksberg** [comment]
This is working fine for me:
```
modules: [
    ['nuxt-validate', {
        fieldsBagName: 'veeFields',
        errorBagName: 'veeErrors',
     }],
],
```

I think you guys have a different problem or are using an old version.

**Comment by Blemming** [comment]
Yes this was with an older version of nuxt-validate when it used version 2 of vee-validate I believe, no longer relevant, closing.
