### ISSUE TITLE
Message from custom validators doesn't take effect

### ISSUE THREAD

**Issue by MrToxy** [lewyuburi/nuxt-validate#23]
> `nuxt.config.js`
> 
> ```js
> module.exports = {
> /// 
>   /*
>    ** Plugins to load beforve mounting the App
>    */
>   plugins: ["~plugins/validate.js"],
> ///
> }

Alright, but how do you add a validation message?

> /plugins/validate

```export default ({ app }) => {
	app.validator.extend('date', {
		validate: (value) => /^\d{2}([./-])\d{2}\1\d{2}$/.test(value),
		message: 'The {_field_} should be a valid date',
	});
};```

Still outputs the default error message: "The Start Date value is not valid"

**Comment by aaharu** [comment]
This module doesn't support Vee Validate 3.
Maybe it works that changing `message` to `getMessage`.

Vee Validate 2 documents
http://vee-validate.logaretm.com/v2/guide/custom-rules.html#using-the-custom-rule

**Comment by MrToxy** [comment]
> This module doesn't support Vee Validate 3.
> Maybe it works that changing `message` to `getMessage`.
> 
> Vee Validate 2 documents
> http://vee-validate.logaretm.com/v2/guide/custom-rules.html#using-the-custom-rule

That worked! Thanks for the fast reply.

Could you update the docs so it shows this and how to actually create a custom validation?
The only way I was able to find it was by looking at the closed issues since there's no mention of that or my current issue anywhere in the docs.

refer to: https://github.com/lewyuburi/nuxt-validate/issues/18
