### ISSUE TITLE
Add custom validation methods error ?

### ISSUE THREAD

**Issue by bat79a** [lewyuburi/nuxt-validate#24]
Hi.

I'm trying to create a custom rule for a password confirmation without success if someone can help me ?

I have inserted in my nuxt.config.js
```
  plugins: ['~plugins/vee-password.js'],
```

In plugins/vee-password.js
```
import { extend } from 'vee-validate'

extend('password', {
  params: ['target'],
  validate (value, { target }) {
    return value === target
  },
  message: 'Password confirmation does not match'
})
```

And when I start my app I have this error :

<img width="1220" alt="Capture d’écran 2019-11-25 à 15 27 42" src="https://user-images.githubusercontent.com/10594983/69548929-99eb4600-0f98-11ea-99bb-2095a04bb80a.png">

Doc that I have found for this : https://github.com/lewyuburi/nuxt-validate#faq
Thx a lot ;p

**Comment by MrToxy** [comment]
Hi, this was the only way I was able to successfully extend default config, it may work for you 

`export default ({ app }) => {
	app.validator.extend('date', {
		validate: (value) => /^\d{4}([./-])\d{2}\1\d{2}$/.test(value),
		getMessage: (field) => `The ${field} should be a valid date: YYYY-MM-DD`,
	});
};
`

**Comment by bat79a** [comment]
Thx a lot for your answer, but I have migrate to the vuelidate package because I was not able to find a solution before your answer.

Have a nice day.
