### ISSUE TITLE
Language option not described

### ISSUE THREAD

**Issue by sumithsonian** [lewyuburi/nuxt-validate#3]
Hello.
Thank you for a wonderful plugin.

I introduced a plugin and saw it.
However, the language option is not reflected.

I moved "Validator.localize" of plugin.js to the last line, the language was reflected.

Please consider examining the correction.

I am sorry for my poor English.

**Comment by seybsen** [comment]
I opened a pull request to fix this issue: https://github.com/lewyuburi/nuxt-validate/pull/5

**Comment by seybsen** [comment]
@lewyuburi would you mind creating a new release with the fix from https://github.com/lewyuburi/nuxt-validate/pull/5 and closing this issue?

**Comment by lewyuburi** [comment]
@seybsen yes! I'm testing right now for release this :D

**Comment by lewyuburi** [comment]
Thanks for @seybsen for the pull request #5, now available in 0.1.3, thanks all :D
